services:
  - type: web
    name: flask-inventory-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:8000 app:ap"
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
